### ISSUE TITLE
I tested the scripts and got error

### ISSUE THREAD

**Issue by yzhang-github-pub** [aws-samples/amazon-sagemaker-bert-pytorch#4]
I did a test run as is, but got "UnexpectedStatusException: Error for Training job pytorch-training-2020-10-27-16-28-37-955: Failed. Reason: AlgorithmError: ExecuteUserScriptError:
Command "/opt/conda/bin/python train_deploy.py --backend gloo --epochs 1 --num_labels 2".

Any help is appreciated.

This is the standout from beginning of running train_deploy.py:

'create_image_uri' will be deprecated in favor of 'ImageURIProvider' class in SageMaker Python SDK v2.
's3_input' class will be renamed to 'TrainingInput' in SageMaker Python SDK v2.
's3_input' class will be renamed to 'TrainingInput' in SageMaker Python SDK v2.
'create_image_uri' will be deprecated in favor of 'ImageURIProvider' class in SageMaker Python SDK v2.
2020-10-27 16:28:38 Starting - Starting the training job...
2020-10-27 16:28:42 Starting - Launching requested ML instances.........
2020-10-27 16:30:13 Starting - Preparing the instances for training............
2020-10-27 16:32:19 Downloading - Downloading input data...
2020-10-27 16:33:09 Training - Downloading the training image..
**bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell**

Not sure training failure is related to above warnings

**Comment by spacer730** [comment]
I have the same issue, whereas before the training would run...

**Comment by akbapu14** [comment]
I changed the PyTorch version to 1.6.0 and it resolved this for me!

**Comment by yzhang-github-pub** [comment]
@akbapu14: Indeed it worked with 1.6.0. However, it gave a lot warnings. Were you successful with 1.3.1 before?  If so were results comparable between 1.3.1 and 1.6.0?

**Comment by billdoors** [comment]
Yes, when this repo was created, it was using 1.3.1. Supported versions: https://github.com/aws/deep-learning-containers/blob/master/available_images.md

I have updated the version number on training to 1.6.0. It seems working. I also updated a few lines to reflect SageMaker Python SDK 2.x change.
