### ISSUE TITLE
Sample nonfunctional for all pytorch frameworks 

### ISSUE THREAD

**Issue by aarsanjani** [aws-samples/amazon-sagemaker-bert-pytorch#6]
Compilation with 1,6.0 works, but deployment fails, no model.pth file created in the sample dir /folder structure anticipated by Huggingface 2.3.0

**Comment by aarsanjani** [comment]
I have found a series of fixes. I will update and merge changes

**Comment by akbapu14** [comment]
@aarsanjani update here on the fixes specifically related to deploying the endpoint?
