### ISSUE TITLE
ValueError: framework_version or py_version was None, yet image_uri was also None. Either specify both framework_version and py_version, or specify image_uri.

### ISSUE THREAD

**Issue by CloudaYolla** [aws-samples/amazon-sagemaker-bert-pytorch#7]
The code below generates an error: 

```
from sagemaker.pytorch.model import PyTorchModel 

pytorch_model = PyTorchModel(# model_data="<S3 location>/model.tar.gz",
                             model_data="s3://sagemaker-us-east-2-503254810580/pytorch-training-2020-11-15-14-28-24-539/model.tar.gz",
                             role=role,
                             framework_version="1.3.1",
                             py_version="py3", # https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/sagemaker.pytorch.html
                             source_dir="code",
                             entry_point="train_deploy.py")

predictor = pytorch_model.deploy(initial_instance_count=1, instance_type="ml.m4.xlarge")

```

Error received:

`ValueError: framework_version or py_version was None, yet image_uri was also None. Either specify both framework_version and py_version, or specify image_uri.
`

Resolution: Adding py_version resolves the error:

```
from sagemaker.pytorch.model import PyTorchModel 

pytorch_model = PyTorchModel(# model_data="<S3 location>/model.tar.gz",
                             model_data="s3://sagemaker-us-east-2-503254810580/pytorch-training-2020-11-15-14-28-24-539/model.tar.gz",
                             role=role,
                             framework_version="1.3.1",
                             py_version="py3", # https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/sagemaker.pytorch.html
                             source_dir="code",
                             entry_point="train_deploy.py")
```

predictor = pytorch_model.deploy(initial_instance_count=1, instance_type="ml.m4.xlarge")

https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/sagemaker.pytorch.html

**Comment by billdoors** [comment]
thanks!

**Comment by ballcap231** [comment]
W

> The code below generates an error:
> 
> ```
> from sagemaker.pytorch.model import PyTorchModel 
> 
> pytorch_model = PyTorchModel(# model_data="<S3 location>/model.tar.gz",
>                              model_data="s3://sagemaker-us-east-2-503254810580/pytorch-training-2020-11-15-14-28-24-539/model.tar.gz",
>                              role=role,
>                              framework_version="1.3.1",
>                              py_version="py3", # https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/sagemaker.pytorch.html
>                              source_dir="code",
>                              entry_point="train_deploy.py")
> 
> predictor = pytorch_model.deploy(initial_instance_count=1, instance_type="ml.m4.xlarge")
> ```
> 
> Error received:
> 
> `ValueError: framework_version or py_version was None, yet image_uri was also None. Either specify both framework_version and py_version, or specify image_uri. `
> 
> Resolution: Adding py_version resolves the error:
> 
> ```
> from sagemaker.pytorch.model import PyTorchModel 
> 
> pytorch_model = PyTorchModel(# model_data="<S3 location>/model.tar.gz",
>                              model_data="s3://sagemaker-us-east-2-503254810580/pytorch-training-2020-11-15-14-28-24-539/model.tar.gz",
>                              role=role,
>                              framework_version="1.3.1",
>                              py_version="py3", # https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/sagemaker.pytorch.html
>                              source_dir="code",
>                              entry_point="train_deploy.py")
> ```
> 
> predictor = pytorch_model.deploy(initial_instance_count=1, instance_type="ml.m4.xlarge")
> 
> https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/sagemaker.pytorch.html

What's the difference between your 2 pieces of code? They look identical.

**Comment by mannusillegal** [comment]
> framework_version="1.3.1",

really helpful

**Comment by aliftadvantage** [comment]
Just choose your image_uri from here: 
https://github.com/aws/deep-learning-containers/blob/master/available_images.md

Per:
https://discuss.huggingface.co/t/error-deploying-bert-on-sagemaker/8401/4
